# Clave única del proyecto en Sonar
sonar.projectKey=zackspike_cicd-test

sonar.organization=zackspike

# Nombre descriptivo
sonar.projectName=cicd-test
sonar.projectVersion=1.0

# Rutas de código fuente y pruebas
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/tests.py,src/**/test_*.py
sonar.exclusions=src/tests.py,src/**/__pycache__/**

# Configuración de Python y Cobertura
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8