# nombre para identificar el workflow
name: Test and Build

# eventos disparadores
on:
  # cuando haga un push en master o una pull request hacia la master
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# los permisos se pueden definir globalmente 
# o unitariamente para cada job

# qué se tiene que ejecutar en este pipeline
jobs:
  # Job CI
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # básico, leer el código de la rama
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: 'src/requirements.txt'

      # actividad para instalar las dependencias, se centra en instalar las bibliotecas, módulos o extensiones que
      # requiere el proyecto para correr, en un caso sencillo únicamente `pip install -r requirements.txt`

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt


      - name: Check linting
        working-directory: src
        run: ruff check .
      # actividad para realizar los tests, en este caso especifíco se determina en cual archivo (por defecto, `pytest`)

      # 2. Ejecutar tests generando reporte XML de cobertura
      - name: Test with pytest and generate coverage
        run: |
          PYTHONPATH=src pytest --cov=src --cov-report=xml:coverage.xml src/tests.py
      # 3. Análisis de SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Discord notification
        if: failure()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'Fallo de implementación.'
    
  # CD - Solo si los tests pasan
  build-and-push:
    needs: [test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # actividades que se realizaran paso a paso
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Project Package Container Publish
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker Image
      uses: docker/build-push-action@v7
      with:
        context: .
        push: true
        tags: ghcr.io/zackspike/cicd-test:latest

    # indicar el tipo de versión del lenguaje
    - name: Discord notification
      if: always()
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: 'Commit ${{ github.sha }} por ${{ github.actor }}'
        ## otros ejemplos:
        # args: 'Pipeline finalizada con estado: ${{ job.status }}'